#!/bin/sh

if [ "$LEFTHOOK_VERBOSE" = "1" -o "$LEFTHOOK_VERBOSE" = "true" ]; then
  set -x
fi

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

call_lefthook()
{
  if test -n "$LEFTHOOK_BIN"
  then
    "$LEFTHOOK_BIN" "$@"
  elif lefthook -h >/dev/null 2>&1
  then
    lefthook "$@"
  elif /mnt/c/Users/colli/Documents/Project/prometheus-site/node_modules/lefthook-linux-arm64/bin/lefthook -h >/dev/null 2>&1
  then
    /mnt/c/Users/colli/Documents/Project/prometheus-site/node_modules/lefthook-linux-arm64/bin/lefthook "$@"
  else
    dir="$(git rev-parse --show-toplevel)"
    osArch=$(uname | tr '[:upper:]' '[:lower:]')
    case "$osArch" in
      mingw*|msys*|cygwin*) osArch="windows" ;;
    esac
    cpuArch=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x64/;s/amd64/x64/')
    if test "$osArch" = "windows"
    then
      if test -f "$dir/node_modules/lefthook-windows-${cpuArch}/bin/lefthook.exe"
      then
        "$dir/node_modules/lefthook-windows-${cpuArch}/bin/lefthook.exe" "$@"
        return
      elif test -f "$dir/node_modules/lefthook-windows-x64/bin/lefthook.exe"
      then
        "$dir/node_modules/lefthook-windows-x64/bin/lefthook.exe" "$@"
        return
      elif test -f "$dir/node_modules/lefthook-windows-arm64/bin/lefthook.exe"
      then
        "$dir/node_modules/lefthook-windows-arm64/bin/lefthook.exe" "$@"
        return
      else
        echo "Lefthook Windows binary not found. Run bun install in Windows or set LEFTHOOK=0 to bypass." >&2
        return 0
      fi
    fi
    if test -f "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook"
    then
      "$dir/node_modules/lefthook-${osArch}-${cpuArch}/bin/lefthook" "$@"
    elif test -f "$dir/node_modules/@evilmartians/lefthook/bin/lefthook-${osArch}-${cpuArch}/lefthook"
    then
      "$dir/node_modules/@evilmartians/lefthook/bin/lefthook-${osArch}-${cpuArch}/lefthook" "$@"
    elif test -f "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook"
    then
      "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook" "$@"
    elif test -f "$dir/node_modules/lefthook/bin/index.js"
    then
      "$dir/node_modules/lefthook/bin/index.js" "$@"
    elif go tool lefthook -h >/dev/null 2>&1
    then
      go tool lefthook "$@"
    elif bundle exec lefthook -h >/dev/null 2>&1
    then
      bundle exec lefthook "$@"
    elif yarn lefthook -h >/dev/null 2>&1
    then
      yarn lefthook "$@"
    elif pnpm lefthook -h >/dev/null 2>&1
    then
      pnpm lefthook "$@"
    elif swift package lefthook >/dev/null 2>&1
    then
      swift package --build-path .build/lefthook --disable-sandbox lefthook "$@"
    elif command -v mint >/dev/null 2>&1
    then
      mint run csjones/lefthook-plugin "$@"
    elif uv run lefthook -h >/dev/null 2>&1
    then
      uv run lefthook "$@"
    elif mise exec -- lefthook -h >/dev/null 2>&1
    then
      mise exec -- lefthook "$@"
    elif devbox run lefthook -h >/dev/null 2>&1
    then
      devbox run lefthook "$@"
    else
      echo "Can't find lefthook in PATH"
    fi
  fi
}

call_lefthook run "prepare-commit-msg" "$@"
