export * from './config'
export * from './shared/lab-copy'
export * from './shared/lang-store'
export * from './shared/lang-bridge'
export * from './shared/ui-copy'
export * from './shared/fragment-copy'
export * from './shared/nav-order'
export * from './fragment/definitions/home'
