import { component$, Slot } from '@builder.io/qwik'
import { Link, useDocumentHead, useLocation } from '@builder.io/qwik-city'

export const RouterHead = component$(() => {
  const head = useDocumentHead()
  const loc = useLocation()
  return (
    <>
      <title>{head.title || 'Prometheus'}</title>
      <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
      <link rel="canonical" href={loc.url.href} />
      {head.meta.map((m) => (
        <meta key={m.key} {...m} />
      ))}
      {head.links.map((l) => (
        <link key={l.key} {...l} />
      ))}
      {head.styles.map((s) => (
        // biome-ignore lint/security/noDangerouslySetInnerHtml: content generated by Qwik head
        <style key={s.key} {...s.props} dangerouslySetInnerHTML={s.style} />
      ))}
      {/* Speculation Rules payload for supported browsers */}
      {// biome-ignore lint/security/noDangerouslySetInnerHtml: controlled static payload
      <script
        type="speculationrules"
        dangerouslySetInnerHTML={`{"prerender":[{"source":"document","where":{"href_matches":"/store"}}],"prefetch":[{"source":"document","where":{"href_matches":"/chat"}}]}`}
      />} 
      {// biome-ignore lint/security/noDangerouslySetInnerHtml: small feature-detect script
      <script
        dangerouslySetInnerHTML={`if ('documentStartViewTransition' in document) {document.documentElement.classList.add('supports-view-transition');}`}
      />}
    </>
  )
})

export default component$(() => (
  <div class="min-h-screen bg-gradient-to-b from-slate-950 via-slate-900 to-slate-950">
    <header class="sticky top-0 z-20 border-b border-slate-800 bg-slate-950/80 backdrop-blur">
      <nav class="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 text-sm font-medium">
        <div class="flex items-center gap-2">
          <span class="rounded-full bg-emerald-500/10 px-3 py-1 text-emerald-300">Prometheus</span>
          <span class="text-slate-400">Performance Lab</span>
        </div>
        <div class="flex items-center gap-4 text-slate-200">
          <Link href="/" class="hover:text-emerald-300 transition-colors view-transition">
            Home
          </Link>
          <Link href="/store" class="hover:text-emerald-300 transition-colors view-transition">
            Store
          </Link>
          <Link href="/chat" class="hover:text-emerald-300 transition-colors view-transition">
            Chat
          </Link>
          <Link href="/ai" class="hover:text-emerald-300 transition-colors view-transition">
            AI
          </Link>
        </div>
      </nav>
    </header>
    <main class="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-10">
      <Slot />
    </main>
  </div>
))
