// This file is auto-generated by scripts/fragment-css.ts. Do not edit.
export const fragmentCssManifest = {
  "fragment://page/chat/contacts@v1": { path: "fragments/fragment-02e5aaec0e8c.css" },
  "fragment://page/store/cart@v1": { path: "fragments/fragment-3a8ecd56b287.css" },
  "fragment://page/store/create@v1": { path: "fragments/fragment-3a8ecd56b287.css" },
  "fragment://page/store/stream@v5": { path: "fragments/fragment-3a8ecd56b287.css" },
} as const

export type FragmentCssManifest = typeof fragmentCssManifest
