// This file is auto-generated by scripts/fragment-css.ts. Do not edit.
export const fragmentCssManifest = {
  "fragment://page/chat/contacts@v1": { path: "fragments/fragment-f913ca683316.css" },
  "fragment://page/store/cart@v1": { path: "fragments/fragment-28e6e9348c7a.css" },
  "fragment://page/store/create@v1": { path: "fragments/fragment-28e6e9348c7a.css" },
  "fragment://page/store/stream@v5": { path: "fragments/fragment-28e6e9348c7a.css" },
} as const

export type FragmentCssManifest = typeof fragmentCssManifest
