// This file is auto-generated by scripts/fragment-css.ts. Do not edit.
export const fragmentCssManifest = {
  "fragment://page/chat/contacts@v1": { path: "fragments/fragment-a1d4d8fc3b02.css" },
  "fragment://page/store/cart@v1": { path: "fragments/fragment-bddbb00bca57.css" },
  "fragment://page/store/create@v1": { path: "fragments/fragment-bddbb00bca57.css" },
  "fragment://page/store/stream@v5": { path: "fragments/fragment-bddbb00bca57.css" },
} as const

export type FragmentCssManifest = typeof fragmentCssManifest
