import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

type CssManifestEntry = {
  path: string
}

type CssOutput = {
  fileName: string
  css: string
}

const defaultRepoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const fragmentDefinitionSources = [
  'apps/site/src/fragment/definitions/home.server.ts',
  'apps/site/src/fragment/definitions/store.ts',
  'apps/site/src/fragment/definitions/chat.ts'
]

const parseTemplateConstants = (source: string) => {
  const map = new Map<string, string>()
  const pattern = /const\s+([A-Za-z_$][\w$]*)\s*=\s*`([\s\S]*?)`/g
  let match: RegExpExecArray | null = pattern.exec(source)
  while (match) {
    map.set(match[1], match[2])
    match = pattern.exec(source)
  }
  return map
}

const unquoteCssToken = (token: string) => {
  if (token.length < 2) return token
  const quote = token[0]
  const endQuote = token[token.length - 1]
  if (quote !== endQuote) return token
  if (quote === '`') return token.slice(1, -1)
  if (quote === '"') {
    try {
      return JSON.parse(token) as string
    } catch {
      return token.slice(1, -1)
    }
  }
  if (quote === "'") return token.slice(1, -1).replace(/\\'/g, "'").replace(/\\\\/g, '\\')
  return token
}

const collectFragmentCssEntries = (source: string, templateConstants: Map<string, string>) => {
  const entries: Array<{ id: string; css: string }> = []
  const idPattern = /id:\s*(['"`])(fragment:\/\/[^'"`]+)\1/g
  let idMatch: RegExpExecArray | null = idPattern.exec(source)
  while (idMatch) {
    const id = idMatch[2]
    const windowStart = idMatch.index
    const windowEnd = Math.min(source.length, windowStart + 600)
    const windowSource = source.slice(windowStart, windowEnd)
    const cssMatch = /css:\s*([^,\n]+)/.exec(windowSource)
    if (cssMatch) {
      const cssToken = cssMatch[1].trim()
      let css = ''
      if (cssToken.startsWith("'") || cssToken.startsWith('"') || cssToken.startsWith('`')) {
        css = unquoteCssToken(cssToken)
      } else {
        css = templateConstants.get(cssToken) ?? ''
      }
      const normalized = css.trim()
      if (normalized.length > 0) entries.push({ id, css: normalized })
    }
    idMatch = idPattern.exec(source)
  }
  return entries
}

const resolveCssEntries = (repoRoot: string) =>
  fragmentDefinitionSources.flatMap((relativePath) => {
    const sourcePath = resolve(repoRoot, relativePath)
    const source = readFileSync(sourcePath, 'utf8')
    const templateConstants = parseTemplateConstants(source)
    return collectFragmentCssEntries(source, templateConstants)
  })

export const generateFragmentCss = (repoRoot: string = defaultRepoRoot) => {
  const outputDir = resolve(repoRoot, 'apps/site/public/fragments')
  const manifestPath = resolve(repoRoot, 'apps/site/src/fragment/fragment-css.generated.ts')
  const cssEntries = resolveCssEntries(repoRoot)
  const cssByContent = new Map<string, CssManifestEntry & { fileName: string }>()
  const outputs: CssOutput[] = []
  const manifestEntries: Array<[string, CssManifestEntry]> = []

  cssEntries.forEach(({ id, css }) => {
    let entry = cssByContent.get(css)
    if (!entry) {
      const hash = createHash('sha256').update(css).digest('hex').slice(0, 12)
      const fileName = `fragment-${hash}.css`
      entry = { fileName, path: `fragments/${fileName}` }
      cssByContent.set(css, entry)
      outputs.push({ fileName, css })
    }
    manifestEntries.push([id, { path: entry.path }])
  })

  manifestEntries.sort(([a], [b]) => a.localeCompare(b))

  rmSync(outputDir, { recursive: true, force: true })
  mkdirSync(outputDir, { recursive: true })
  outputs.forEach(({ fileName, css }) => {
    const target = resolve(outputDir, fileName)
    writeFileSync(target, `${css.trim()}\n`)
  })

  const lines: string[] = []
  lines.push('// This file is auto-generated by scripts/fragment-css.ts. Do not edit.')
  lines.push('export const fragmentCssManifest = {')
  manifestEntries.forEach(([id, entry]) => {
    lines.push(`  ${JSON.stringify(id)}: { path: ${JSON.stringify(entry.path)} },`)
  })
  lines.push('} as const')
  lines.push('')
  lines.push('export type FragmentCssManifest = typeof fragmentCssManifest')
  lines.push('')

  writeFileSync(manifestPath, lines.join('\n'))
}

const isScriptEntrypoint = () => {
  const argvPath = process.argv[1]
  if (!argvPath) return false
  return resolve(argvPath) === fileURLToPath(import.meta.url)
}

if (isScriptEntrypoint()) {
  generateFragmentCss()
}
