import { createHash } from 'node:crypto'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'

import { clearFragmentDefinitions, getAllFragmentDefinitions } from '../packages/core/src/fragment/registry'

type CssManifestEntry = {
  path: string
}

type CssOutput = {
  fileName: string
  css: string
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputDir = resolve(repoRoot, 'apps/site/public/fragments')
const manifestPath = resolve(repoRoot, 'apps/site/src/fragment/fragment-css.generated.ts')

const importModule = async (relativePath: string) => {
  const target = resolve(repoRoot, relativePath)
  await import(pathToFileURL(target).href)
}

clearFragmentDefinitions()
await importModule('apps/site/src/fragment/definitions/home.server.ts')
await importModule('apps/site/src/fragment/definitions/store.ts')
await importModule('apps/site/src/fragment/definitions/chat.ts')

const definitions = getAllFragmentDefinitions()
const cssEntries = definitions
  .map((definition) => ({ id: definition.id, css: definition.css?.trim() ?? '' }))
  .filter((entry) => entry.css.length > 0)

const cssByContent = new Map<string, CssManifestEntry & { fileName: string }>()
const outputs: CssOutput[] = []
const manifestEntries: Array<[string, CssManifestEntry]> = []

cssEntries.forEach(({ id, css }) => {
  let entry = cssByContent.get(css)
  if (!entry) {
    const hash = createHash('sha256').update(css).digest('hex').slice(0, 12)
    const fileName = `fragment-${hash}.css`
    entry = { fileName, path: `fragments/${fileName}` }
    cssByContent.set(css, entry)
    outputs.push({ fileName, css })
  }
  manifestEntries.push([id, { path: entry.path }])
})

manifestEntries.sort(([a], [b]) => a.localeCompare(b))

rmSync(outputDir, { recursive: true, force: true })
mkdirSync(outputDir, { recursive: true })
outputs.forEach(({ fileName, css }) => {
  const target = resolve(outputDir, fileName)
  writeFileSync(target, `${css.trim()}\n`)
})

const lines: string[] = []
lines.push('// This file is auto-generated by scripts/fragment-css.ts. Do not edit.')
lines.push('export const fragmentCssManifest = {')
manifestEntries.forEach(([id, entry]) => {
  lines.push(`  ${JSON.stringify(id)}: { path: ${JSON.stringify(entry.path)} },`)
})
lines.push('} as const')
lines.push('')
lines.push('export type FragmentCssManifest = typeof fragmentCssManifest')
lines.push('')

writeFileSync(manifestPath, lines.join('\n'))
